// lib/pages/add_edit_product_page.dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../controllers/product_controller.dart';
import '../../controllers/category_controller.dart';
import '../../controllers/brand_controller.dart';
import '../../controllers/unit_controller.dart';
import '../../controllers/auth_controller.dart';
import '../../models/product_model.dart';

class AddEditProductPage extends StatefulWidget {
  final Product? product;
  const AddEditProductPage({Key? key, this.product}) : super(key: key);

  @override
  State<AddEditProductPage> createState() => _AddEditProductPageState();
}

class _AddEditProductPageState extends State<AddEditProductPage> {
  // ── Brand tokens ────────────────────────────────────────────────────────────
  static const _navy = Color(0xFF0F1729);
  static const _navyLight = Color(0xFF1A2744);
  static const _emerald = Color(0xFF10B981);
  static const _emeraldLight = Color(0xFFD1FAE5);
  static const _rose = Color(0xFFE11D48);
  static const _sky = Color(0xFF0EA5E9);
  static const _skyLight = Color(0xFFE0F2FE);
  static const _canvas = Color(0xFFF7F8FC);
  static const _surface = Color(0xFFFFFFFF);
  static const _border = Color(0xFFE2E8F0);
  static const _textPrimary = Color(0xFF0F172A);
  static const _textSecondary = Color(0xFF64748B);

  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _purchaseRateController = TextEditingController();
  final _saleRateController = TextEditingController();
  final _taxPercentageController = TextEditingController();
  final _openingQtyController = TextEditingController();
  final _pctCodeController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _barcodeController = TextEditingController();

  int? _selectedCategoryId;
  int? _selectedBrandId;
  int? _selectedUnitId;
  bool _barcodeAutoGenerated = true;
  bool _isLoading = false;

  // New variables for item code and barcode generation
  String _itemCode = '';
  String _generatedBarcode = '';

  // Net rate calculation
  double _netRate = 0.0;

  bool get _isEditing => widget.product != null;

  @override
  void initState() {
    super.initState();

    // Load dropdown data and generate codes
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      await _loadDropdownData();
      _generateCodes();
    });

    if (_isEditing) {
      // Pre-fill editing data
      _nameController.text = widget.product!.name;
      _purchaseRateController.text = widget.product!.purchaseRate.toString();
      _saleRateController.text = widget.product!.saleRate.toString();
      _taxPercentageController.text = widget.product!.taxPercentage.toString();
      _openingQtyController.text = widget.product!.openingQty.toString();
      _pctCodeController.text = widget.product!.pctCode ?? '';
      _descriptionController.text = widget.product!.description;
      _selectedCategoryId = widget.product!.categoryId;
      _selectedBrandId = widget.product!.brandId;
      _selectedUnitId = widget.product!.unitId;
      _barcodeAutoGenerated = widget.product!.barcodeAutoGenerated;

      // Use existing codes for editing
      _itemCode = widget.product!.itemCode;
      if (!_barcodeAutoGenerated && widget.product!.barcode != null) {
        _barcodeController.text = widget.product!.barcode!;
        _generatedBarcode = widget.product!.barcode!;
      } else {
        _generatedBarcode = widget.product!.barcode ?? '';
        _barcodeController.text = _generatedBarcode;
      }

      // Calculate net rate for editing
      _calculateNetRate();
    }

    // Add listeners to recalculate net rate when sale rate or tax changes
    _saleRateController.addListener(_calculateNetRate);
    _taxPercentageController.addListener(_calculateNetRate);
  }

  Future<void> _loadDropdownData() async {
    final categoryController = context.read<CategoryController>();
    final brandController = context.read<BrandController>();
    final unitController = context.read<UnitController>();

    await Future.wait([
      categoryController.fetchCategories(),
      brandController.fetchBrands(),
      unitController.fetchUnits(),
    ]);
  }

  // ── Code Generation Methods ─────────────────────────────────────────────────

  void _generateCodes() {
    if (_isEditing) return; // Don't generate new codes when editing

    // Get the next item code from the product controller
    final productController = context.read<ProductController>();
    _itemCode = _generateNextItemCode(productController.products);

    // Generate barcode if auto-generated
    if (_barcodeAutoGenerated) {
      _generatedBarcode = _generateBarcode();
      _barcodeController.text = _generatedBarcode;
    }

    setState(() {});
  }

  String _generateNextItemCode(List<Product> products) {
    // If no products exist, start with 1
    if (products.isEmpty) {
      return 'PRD-0001';
    }

    // Find the highest item code number
    int maxNumber = 0;
    for (var product in products) {
      // Extract number from item code (assuming format PRD-XXXX)
      final parts = product.itemCode.split('-');
      if (parts.length == 2) {
        final number = int.tryParse(parts[1]);
        if (number != null && number > maxNumber) {
          maxNumber = number;
        }
      }
    }

    // Generate next number with leading zeros
    final nextNumber = maxNumber + 1;
    return 'PRD-${nextNumber.toString().padLeft(4, '0')}';
  }

  String _generateBarcode() {
    // Generate a unique barcode based on current timestamp
    // You can customize this based on your requirements
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final random = DateTime.now().microsecond % 10000;
    return 'BAR${timestamp.toString().substring(timestamp.toString().length - 8)}${random.toString().padLeft(4, '0')}';
  }

  // ── Net Rate Calculation ────────────────────────────────────────────────────

  void _calculateNetRate() {
    setState(() {
      final saleRate = double.tryParse(_saleRateController.text) ?? 0.0;
      final taxPercentage = double.tryParse(_taxPercentageController.text) ?? 0.0;
      _netRate = saleRate + (saleRate * taxPercentage / 100);
    });
  }

  @override
  void dispose() {
    _nameController.dispose();
    _purchaseRateController.dispose();
    _saleRateController.dispose();
    _taxPercentageController.dispose();
    _openingQtyController.dispose();
    _pctCodeController.dispose();
    _descriptionController.dispose();
    _barcodeController.dispose();
    // Remove listeners
    _saleRateController.removeListener(_calculateNetRate);
    _taxPercentageController.removeListener(_calculateNetRate);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: _canvas,
      body: Row(
        children: [
          _buildSidebar(context),
          Expanded(
            child: Column(
              children: [
                _buildTopBar(context),
                Expanded(
                  child: Center(
                    child: SingleChildScrollView(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 28, vertical: 32),
                      child: ConstrainedBox(
                        constraints: const BoxConstraints(maxWidth: 700),
                        child: _buildFormCard(),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // ── Sidebar ──────────────────────────────────────────────────────────────────

  Widget _buildSidebar(BuildContext context) {
    return Container(
      width: 220,
      color: _navy,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(20, 32, 20, 32),
            child: Row(
              children: [
                Container(
                  width: 32,
                  height: 32,
                  decoration: BoxDecoration(
                      color: _emerald,
                      borderRadius: BorderRadius.circular(8)),
                  child: const Icon(Icons.point_of_sale,
                      color: Colors.white, size: 18),
                ),
                const SizedBox(width: 10),
                const Text('POSify',
                    style: TextStyle(
                        color: Colors.white,
                        fontSize: 18,
                        fontWeight: FontWeight.w700,
                        letterSpacing: -0.3)),
              ],
            ),
          ),
          _navItem(Icons.grid_view_rounded, 'Dashboard',
              onTap: () => Navigator.popUntil(context, (r) => r.isFirst)),
          _navItem(Icons.shopping_cart_outlined, 'New Sale'),
          _navItem(Icons.inventory_2_outlined, 'Products',
              active: true, onTap: () => Navigator.pop(context)),
          _navItem(Icons.bar_chart_rounded, 'Reports'),
          _navItem(Icons.people_outline_rounded, 'Users'),
          const Spacer(),
          Padding(
            padding: const EdgeInsets.fromLTRB(12, 0, 12, 28),
            child: TextButton.icon(
              onPressed: () async {
                await context.read<AuthController>().logout();
                Navigator.pushReplacementNamed(context, '/login');
              },
              icon: const Icon(Icons.logout,
                  size: 16, color: Color(0xFF94A3B8)),
              label: const Text('Sign out',
                  style: TextStyle(color: Color(0xFF94A3B8), fontSize: 13)),
              style: TextButton.styleFrom(
                padding:
                const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                alignment: Alignment.centerLeft,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _navItem(IconData icon, String label,
      {bool active = false, VoidCallback? onTap}) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 2),
      child: Material(
        color: active ? _navyLight : Colors.transparent,
        borderRadius: BorderRadius.circular(8),
        child: InkWell(
          onTap: onTap,
          borderRadius: BorderRadius.circular(8),
          hoverColor: _navyLight,
          child: Padding(
            padding:
            const EdgeInsets.symmetric(horizontal: 12, vertical: 11),
            child: Row(
              children: [
                Icon(icon,
                    size: 18,
                    color: active ? _emerald : const Color(0xFF94A3B8)),
                const SizedBox(width: 10),
                Text(label,
                    style: TextStyle(
                      color: active ? Colors.white : const Color(0xFF94A3B8),
                      fontSize: 13.5,
                      fontWeight:
                      active ? FontWeight.w600 : FontWeight.w400,
                    )),
                if (active) ...[
                  const Spacer(),
                  Container(
                      width: 4,
                      height: 4,
                      decoration: const BoxDecoration(
                          color: _emerald, shape: BoxShape.circle)),
                ],
              ],
            ),
          ),
        ),
      ),
    );
  }

  // ── Top bar ──────────────────────────────────────────────────────────────────

  Widget _buildTopBar(BuildContext context) {
    return Container(
      height: 64,
      padding: const EdgeInsets.symmetric(horizontal: 28),
      decoration: const BoxDecoration(
        color: _surface,
        border: Border(bottom: BorderSide(color: _border)),
      ),
      child: Row(
        children: [
          GestureDetector(
            onTap: () => Navigator.popUntil(context, (r) => r.isFirst),
            child: const Text('Dashboard',
                style: TextStyle(fontSize: 13, color: _textSecondary)),
          ),
          const Padding(
            padding: EdgeInsets.symmetric(horizontal: 6),
            child:
            Icon(Icons.chevron_right, size: 14, color: _textSecondary),
          ),
          GestureDetector(
            onTap: () => Navigator.pop(context),
            child: const Text('Products',
                style: TextStyle(fontSize: 13, color: _textSecondary)),
          ),
          const Padding(
            padding: EdgeInsets.symmetric(horizontal: 6),
            child:
            Icon(Icons.chevron_right, size: 14, color: _textSecondary),
          ),
          Text(_isEditing ? 'Edit Product' : 'Add Product',
              style: const TextStyle(
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                  color: _textPrimary)),
        ],
      ),
    );
  }

  // ── Form card ────────────────────────────────────────────────────────────────

  Widget _buildFormCard() {
    return Container(
      decoration: BoxDecoration(
        color: _surface,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: _border),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.04),
            blurRadius: 12,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Card header
          Container(
            padding: const EdgeInsets.fromLTRB(28, 24, 28, 20),
            decoration: const BoxDecoration(
              border: Border(bottom: BorderSide(color: _border)),
            ),
            child: Row(
              children: [
                Container(
                  width: 40,
                  height: 40,
                  decoration: BoxDecoration(
                    color: _isEditing ? _emeraldLight : _skyLight,
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: Icon(
                    _isEditing
                        ? Icons.edit_outlined
                        : Icons.add_business_outlined,
                    size: 20,
                    color: _isEditing ? _emerald : _sky,
                  ),
                ),
                const SizedBox(width: 14),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      _isEditing ? 'Edit Product' : 'Add New Product',
                      style: const TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w700,
                        color: _textPrimary,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      _isEditing
                          ? 'Update the details for this product.'
                          : 'Fill in the details to add to inventory.',
                      style: const TextStyle(
                          fontSize: 12, color: _textSecondary),
                    ),
                  ],
                ),
              ],
            ),
          ),

          // Form body
          Padding(
            padding: const EdgeInsets.all(28),
            child: Form(
              key: _formKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // Two columns layout for better organization
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Expanded(
                        child: Column(
                          children: [
                            // Item Code (Auto-generated - Display only)
                            _fieldLabel('Item Code'),
                            const SizedBox(height: 6),
                            _buildDisplayField(
                              text: _itemCode.isNotEmpty ? _itemCode : 'Will be auto-generated',
                              icon: Icons.code,
                            ),
                            const SizedBox(height: 16),

                            // Barcode
                            _fieldLabel('Barcode'),
                            const SizedBox(height: 6),
                            Row(
                              children: [
                                Expanded(
                                  child: _buildTextField(
                                    controller: _barcodeController,
                                    hint: _barcodeAutoGenerated
                                        ? 'Auto-generated'
                                        : 'Enter barcode',
                                    icon: Icons.qr_code,
                                    enabled: !_barcodeAutoGenerated,
                                    validator: (v) {
                                      if (!_barcodeAutoGenerated &&
                                          (v == null || v.isEmpty)) {
                                        return 'Barcode is required when manual mode is selected';
                                      }
                                      return null;
                                    },
                                  ),
                                ),
                                const SizedBox(width: 8),
                                Row(
                                  children: [
                                    Checkbox(
                                      value: _barcodeAutoGenerated,
                                      onChanged: (value) {
                                        setState(() {
                                          _barcodeAutoGenerated = value ?? true;
                                          if (_barcodeAutoGenerated) {
                                            // Regenerate barcode when switching to auto
                                            _generatedBarcode = _generateBarcode();
                                            _barcodeController.text = _generatedBarcode;
                                          } else {
                                            _barcodeController.clear();
                                          }
                                        });
                                      },
                                      activeColor: _emerald,
                                    ),
                                    const Text(
                                      'Auto',
                                      style: TextStyle(
                                        fontSize: 12,
                                        color: _textSecondary,
                                      ),
                                    ),
                                  ],
                                ),
                              ],
                            ),
                            const SizedBox(height: 16),
                          ],
                        ),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: Column(
                          children: [
                            // Category Dropdown
                            _fieldLabel('Category'),
                            const SizedBox(height: 6),
                            _buildDropdownField<int>(
                              value: _selectedCategoryId,
                              items: context.watch<CategoryController>().categories,
                              itemLabel: (c) => c.name,
                              itemValue: (c) => c.id,
                              hint: 'Select category',
                              onChanged: (value) {
                                setState(() => _selectedCategoryId = value);
                              },
                            ),
                            const SizedBox(height: 16),

                            // Brand Dropdown
                            _fieldLabel('Brand'),
                            const SizedBox(height: 6),
                            _buildDropdownField<int>(
                              value: _selectedBrandId,
                              items: context.watch<BrandController>().brands,
                              itemLabel: (b) => b.name,
                              itemValue: (b) => b.id,
                              hint: 'Select brand',
                              onChanged: (value) {
                                setState(() => _selectedBrandId = value);
                              },
                            ),
                            const SizedBox(height: 16),
                          ],
                        ),
                      ),
                    ],
                  ),

                  // Item Name
                  _fieldLabel('Item Name *'),
                  const SizedBox(height: 6),
                  _buildTextField(
                    controller: _nameController,
                    hint: 'Enter product name',
                    icon: Icons.inventory_2_outlined,
                    validator: (v) => (v == null || v.isEmpty)
                        ? 'Name is required'
                        : null,
                  ),
                  const SizedBox(height: 16),

                  // Unit Dropdown
                  _fieldLabel('Unit'),
                  const SizedBox(height: 6),
                  _buildDropdownField<int>(
                    value: _selectedUnitId,
                    items: context.watch<UnitController>().units,
                    itemLabel: (u) => u.abbreviation.isNotEmpty
                        ? '${u.name} (${u.abbreviation})'
                        : u.name,
                    itemValue: (u) => u.id,
                    hint: 'Select unit',
                    onChanged: (value) {
                      setState(() => _selectedUnitId = value);
                    },
                  ),
                  const SizedBox(height: 16),

                  // Three columns for rates (Purchase, Sale, Tax)
                  Row(
                    children: [
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            _fieldLabel('Purchase Rate *'),
                            const SizedBox(height: 6),
                            _buildTextField(
                              controller: _purchaseRateController,
                              hint: '0.00',
                              icon: Icons.money_off,
                              keyboardType:
                              const TextInputType.numberWithOptions(
                                  decimal: true),
                              validator: (v) {
                                if (v == null || v.isEmpty)
                                  return 'Purchase rate is required';
                                if (double.tryParse(v) == null)
                                  return 'Invalid number';
                                if (double.parse(v) < 0)
                                  return 'Cannot be negative';
                                return null;
                              },
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            _fieldLabel('Sale Rate *'),
                            const SizedBox(height: 6),
                            _buildTextField(
                              controller: _saleRateController,
                              hint: '0.00',
                              icon: Icons.payments_outlined,
                              keyboardType:
                              const TextInputType.numberWithOptions(
                                  decimal: true),
                              validator: (v) {
                                if (v == null || v.isEmpty)
                                  return 'Sale rate is required';
                                if (double.tryParse(v) == null)
                                  return 'Invalid number';
                                if (double.parse(v) < 0)
                                  return 'Cannot be negative';
                                return null;
                              },
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            _fieldLabel('Tax (%)'),
                            const SizedBox(height: 6),
                            _buildTextField(
                              controller: _taxPercentageController,
                              hint: '0',
                              icon: Icons.percent,
                              keyboardType:
                              const TextInputType.numberWithOptions(
                                  decimal: true),
                              validator: (v) {
                                if (v == null || v.isEmpty) return null;
                                if (double.tryParse(v) == null)
                                  return 'Invalid number';
                                final val = double.parse(v);
                                if (val < 0 || val > 100)
                                  return 'Must be 0-100';
                                return null;
                              },
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),

                  // Net Rate (Auto-calculated - Display only)
                  Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: _skyLight,
                      borderRadius: BorderRadius.circular(8),
                      border: Border.all(color: _sky.withOpacity(0.3)),
                    ),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Row(
                          children: [
                            Icon(Icons.calculate, color: _sky, size: 20),
                            const SizedBox(width: 8),
                            const Text(
                              'Net Rate (incl. tax)',
                              style: TextStyle(
                                fontSize: 13,
                                fontWeight: FontWeight.w600,
                                color: _textPrimary,
                              ),
                            ),
                          ],
                        ),
                        Text(
                          '₨ ${_netRate.toStringAsFixed(2)}',
                          style: const TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w700,
                            color: _sky,
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 16),

                  // Two columns for tax and opening qty (Removed tax from here as it's moved above)
                  Row(
                    children: [
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            _fieldLabel('Opening Qty'),
                            const SizedBox(height: 6),
                            _buildTextField(
                              controller: _openingQtyController,
                              hint: '0',
                              icon: Icons.warehouse,
                              keyboardType:
                              const TextInputType.numberWithOptions(
                                  decimal: true),
                              validator: (v) {
                                if (v == null || v.isEmpty) return null;
                                if (double.tryParse(v) == null)
                                  return 'Invalid number';
                                if (double.parse(v) < 0)
                                  return 'Cannot be negative';
                                return null;
                              },
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            _fieldLabel('PCT Code'),
                            const SizedBox(height: 6),
                            _buildTextField(
                              controller: _pctCodeController,
                              hint: 'Enter PCT code',
                              icon: Icons.code_rounded,
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),

                  // Description
                  _fieldLabel('Description (Optional)'),
                  const SizedBox(height: 6),
                  _buildTextField(
                    controller: _descriptionController,
                    hint: 'Brief product notes',
                    icon: Icons.notes_rounded,
                    maxLines: 3,
                  ),
                  const SizedBox(height: 28),

                  // Actions
                  FilledButton(
                    onPressed: _isLoading ? null : _saveProduct,
                    style: FilledButton.styleFrom(
                      backgroundColor: _emerald,
                      disabledBackgroundColor: _emerald.withOpacity(0.5),
                      padding:
                      const EdgeInsets.symmetric(vertical: 14),
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(10)),
                    ),
                    child: _isLoading
                        ? const SizedBox(
                      width: 18,
                      height: 18,
                      child: CircularProgressIndicator(
                          color: Colors.white, strokeWidth: 2),
                    )
                        : Text(
                      _isEditing
                          ? 'Save Changes'
                          : 'Add to Inventory',
                      style: const TextStyle(
                          fontSize: 14,
                          fontWeight: FontWeight.w600),
                    ),
                  ),
                  const SizedBox(height: 12),
                  OutlinedButton(
                    onPressed: () => Navigator.pop(context),
                    style: OutlinedButton.styleFrom(
                      foregroundColor: _textSecondary,
                      side: const BorderSide(color: _border),
                      padding:
                      const EdgeInsets.symmetric(vertical: 14),
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(10)),
                    ),
                    child: const Text('Cancel',
                        style: TextStyle(fontSize: 14)),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _fieldLabel(String text) {
    return Text(text,
        style: const TextStyle(
          fontSize: 12.5,
          fontWeight: FontWeight.w600,
          color: _textSecondary,
        ));
  }

  Widget _buildDisplayField({
    required String text,
    required IconData icon,
  }) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 13),
      decoration: BoxDecoration(
        color: _canvas,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: _border),
      ),
      child: Row(
        children: [
          Icon(icon, size: 17, color: _textSecondary),
          const SizedBox(width: 10),
          Expanded(
            child: Text(
              text,
              style: TextStyle(
                fontSize: 13.5,
                color: text.contains('auto-generated')
                    ? _textSecondary
                    : _textPrimary,
                fontStyle: text.contains('auto-generated')
                    ? FontStyle.italic
                    : FontStyle.normal,
                fontWeight: text.contains('auto-generated')
                    ? FontWeight.normal
                    : FontWeight.w600,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildDropdownField<T>({
    required T? value,
    required List<dynamic> items,
    required String Function(dynamic) itemLabel,
    required T? Function(dynamic) itemValue,
    required String hint,
    required ValueChanged<T?> onChanged,
  }) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 4),
      decoration: BoxDecoration(
        color: _canvas,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: _border),
      ),
      child: DropdownButton<T>(
        value: value,
        isExpanded: true,
        hint: Text(
          hint,
          style: const TextStyle(
            color: _textSecondary,
            fontSize: 13.5,
          ),
        ),
        underline: const SizedBox(),
        items: [
          DropdownMenuItem<T>(
            value: null,
            child: Text(
              'None',
              style: TextStyle(
                fontSize: 13.5,
                color: _textSecondary,
              ),
            ),
          ),
          ...items.map((item) {
            return DropdownMenuItem<T>(
              value: itemValue(item),
              child: Text(
                itemLabel(item),
                style: const TextStyle(
                  fontSize: 13.5,
                  color: _textPrimary,
                ),
              ),
            );
          }),
        ],
        onChanged: onChanged,
        icon: const Icon(Icons.arrow_drop_down, color: _textSecondary),
        dropdownColor: _surface,
        elevation: 4,
        style: const TextStyle(
          fontSize: 13.5,
          color: _textPrimary,
        ),
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String hint,
    required IconData icon,
    TextInputType? keyboardType,
    int maxLines = 1,
    bool enabled = true,
    String? Function(String?)? validator,
  }) {
    return TextFormField(
      controller: controller,
      keyboardType: keyboardType,
      maxLines: maxLines,
      enabled: enabled,
      validator: validator,
      style: TextStyle(
        fontSize: 13.5,
        color: enabled ? _textPrimary : _textSecondary,
      ),
      decoration: InputDecoration(
        hintText: hint,
        hintStyle:
        const TextStyle(color: _textSecondary, fontSize: 13.5),
        prefixIcon: maxLines == 1 && enabled
            ? Icon(icon, size: 17, color: _textSecondary)
            : null,
        filled: true,
        fillColor: enabled ? _canvas : _canvas.withOpacity(0.5),
        contentPadding: EdgeInsets.symmetric(
          horizontal: 14,
          vertical: maxLines > 1 ? 14 : 13,
        ),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: _border),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: _border),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: _emerald, width: 1.5),
        ),
        errorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: _rose),
        ),
        focusedErrorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: _rose, width: 1.5),
        ),
        errorStyle: const TextStyle(fontSize: 11.5, color: _rose),
      ),
    );
  }

  // ── Action ───────────────────────────────────────────────────────────────────

  Future<void> _saveProduct() async {
    if (!_formKey.currentState!.validate()) return;
    setState(() => _isLoading = true);

    final pc = context.read<ProductController>();

    final bool success;
    if (_isEditing) {
      success = await pc.updateProduct(
        id: widget.product!.id,
        name: _nameController.text.trim(),
        purchaseRate: double.parse(_purchaseRateController.text),
        saleRate: double.parse(_saleRateController.text),
        taxPercentage: _taxPercentageController.text.isEmpty
            ? 0
            : double.parse(_taxPercentageController.text),
        openingQty: _openingQtyController.text.isEmpty
            ? 0
            : double.parse(_openingQtyController.text),
        categoryId: _selectedCategoryId,
        brandId: _selectedBrandId,
        unitId: _selectedUnitId,
        pctCode: _pctCodeController.text.trim().isEmpty
            ? null
            : _pctCodeController.text.trim(),
        description: _descriptionController.text.trim(),
        barcode: _barcodeController.text.trim().isEmpty
            ? null
            : _barcodeController.text.trim(),
        barcodeAutoGenerated: _barcodeAutoGenerated,
      );
    } else {
      success = await pc.createProduct(
        name: _nameController.text.trim(),
        purchaseRate: double.parse(_purchaseRateController.text),
        saleRate: double.parse(_saleRateController.text),
        taxPercentage: _taxPercentageController.text.isEmpty
            ? 0
            : double.parse(_taxPercentageController.text),
        openingQty: _openingQtyController.text.isEmpty
            ? 0
            : double.parse(_openingQtyController.text),
        categoryId: _selectedCategoryId,
        brandId: _selectedBrandId,
        unitId: _selectedUnitId,
        pctCode: _pctCodeController.text.trim().isEmpty
            ? null
            : _pctCodeController.text.trim(),
        description: _descriptionController.text.trim(),
        barcode: _barcodeController.text.trim().isEmpty
            ? null
            : _barcodeController.text.trim(),
        barcodeAutoGenerated: _barcodeAutoGenerated,
      );
    }

    setState(() => _isLoading = false);
    if (!mounted) return;

    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
      content: Text(success
          ? (_isEditing ? 'Product updated' : 'Product added to inventory')
          : (pc.errorMessage ?? 'Failed to save product')),
      backgroundColor: success ? _emerald : _rose,
      behavior: SnackBarBehavior.floating,
      shape:
      RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
    ));

    if (success) Navigator.pop(context);
  }
}

