// lib/models/product_model.dart
class Product {
  final int id;
  final String itemCode;
  final String? barcode;
  final bool barcodeAutoGenerated;
  final String name;
  final int? categoryId;
  final String? categoryName;
  final int? brandId;
  final String? brandName;
  final int? unitId;
  final String? unitName;
  final String? unitAbbreviation;
  final double purchaseRate;
  final double saleRate;
  final double taxPercentage;
  final double netRate;
  final double openingQty;
  final String? pctCode;
  final String description;
  final int? createdBy;
  final String createdByName;
  final DateTime createdAt;
  final DateTime updatedAt;

  Product({
    required this.id,
    required this.itemCode,
    this.barcode,
    required this.barcodeAutoGenerated,
    required this.name,
    this.categoryId,
    this.categoryName,
    this.brandId,
    this.brandName,
    this.unitId,
    this.unitName,
    this.unitAbbreviation,
    required this.purchaseRate,
    required this.saleRate,
    required this.taxPercentage,
    required this.netRate,
    required this.openingQty,
    this.pctCode,
    this.description = '',
    this.createdBy,
    this.createdByName = 'Unknown',
    required this.createdAt,
    required this.updatedAt,
  });

  factory Product.fromJson(Map<String, dynamic> json) {
    return Product(
      id: json['id'] ?? 0,
      itemCode: json['item_code'] ?? '',
      barcode: json['barcode'],
      barcodeAutoGenerated: json['barcode_auto_generated'] ?? true,
      name: json['name'] ?? '',
      categoryId: json['category_id'],
      categoryName: json['category_name'],
      brandId: json['brand_id'],
      brandName: json['brand_name'],
      unitId: json['unit_id'],
      unitName: json['unit_name'],
      unitAbbreviation: json['unit_abbreviation'],
      purchaseRate: (json['purchase_rate'] ?? 0).toDouble(),
      saleRate: (json['sale_rate'] ?? 0).toDouble(),
      taxPercentage: (json['tax_percentage'] ?? 0).toDouble(),
      netRate: (json['net_rate'] ?? 0).toDouble(),
      openingQty: (json['opening_qty'] ?? 0).toDouble(),
      pctCode: json['pct_code'],
      description: json['description'] ?? '',
      createdBy: json['created_by'],
      createdByName: json['created_by_name'] ?? 'Unknown',
      createdAt: json['created_at'] != null
          ? DateTime.tryParse(json['created_at'].toString()) ?? DateTime.now()
          : DateTime.now(),
      updatedAt: json['updated_at'] != null
          ? DateTime.tryParse(json['updated_at'].toString()) ?? DateTime.now()
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'item_code': itemCode,
      'barcode': barcode,
      'barcode_auto_generated': barcodeAutoGenerated,
      'name': name,
      'category_id': categoryId,
      'brand_id': brandId,
      'unit_id': unitId,
      'purchase_rate': purchaseRate,
      'sale_rate': saleRate,
      'tax_percentage': taxPercentage,
      'net_rate': netRate,
      'opening_qty': openingQty,
      'pct_code': pctCode,
      'description': description,
      'created_by': createdBy,
      'created_by_name': createdByName,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  Product copyWith({
    int? id,
    String? itemCode,
    String? barcode,
    bool? barcodeAutoGenerated,
    String? name,
    int? categoryId,
    String? categoryName,
    int? brandId,
    String? brandName,
    int? unitId,
    String? unitName,
    String? unitAbbreviation,
    double? purchaseRate,
    double? saleRate,
    double? taxPercentage,
    double? netRate,
    double? openingQty,
    String? pctCode,
    String? description,
    int? createdBy,
    String? createdByName,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Product(
      id: id ?? this.id,
      itemCode: itemCode ?? this.itemCode,
      barcode: barcode ?? this.barcode,
      barcodeAutoGenerated: barcodeAutoGenerated ?? this.barcodeAutoGenerated,
      name: name ?? this.name,
      categoryId: categoryId ?? this.categoryId,
      categoryName: categoryName ?? this.categoryName,
      brandId: brandId ?? this.brandId,
      brandName: brandName ?? this.brandName,
      unitId: unitId ?? this.unitId,
      unitName: unitName ?? this.unitName,
      unitAbbreviation: unitAbbreviation ?? this.unitAbbreviation,
      purchaseRate: purchaseRate ?? this.purchaseRate,
      saleRate: saleRate ?? this.saleRate,
      taxPercentage: taxPercentage ?? this.taxPercentage,
      netRate: netRate ?? this.netRate,
      openingQty: openingQty ?? this.openingQty,
      pctCode: pctCode ?? this.pctCode,
      description: description ?? this.description,
      createdBy: createdBy ?? this.createdBy,
      createdByName: createdByName ?? this.createdByName,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  String toString() =>
      'Product(id: $id, name: $name, itemCode: $itemCode)';
}