// lib/controllers/product_controller.dart
import 'package:flutter/material.dart';
import '../services/api_service.dart';
import '../models/product_model.dart';

class ProductController extends ChangeNotifier {
  final ApiService _apiService;

  List<Product> _products = [];
  bool _isLoading = false;
  String? _errorMessage;

  ProductController({required ApiService apiService})
      : _apiService = apiService;

  List<Product> get products => _products;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;

  // ── Fetch all ──────────────────────────────────────────────────────────────

  Future<void> fetchProducts() async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      final response = await _apiService.getRequest('/products');

      if (response['success'] == true) {
        final List<dynamic> productsJson = response['products'] ?? [];
        _products =
            productsJson.map((json) => Product.fromJson(json)).toList();
      } else {
        _errorMessage = response['message'] ?? 'Failed to load products';
      }
    } catch (e) {
      _errorMessage = 'Error: ${e.toString()}';
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  // ── Create ─────────────────────────────────────────────────────────────────

  Future<bool> createProduct({
    required String name,
    required double purchaseRate,
    required double saleRate,
    double taxPercentage = 0,
    double openingQty = 0,
    int? categoryId,
    int? brandId,
    int? unitId,
    String? pctCode,
    String description = '',
    String? barcode,
    bool barcodeAutoGenerated = true,
  }) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      final response = await _apiService.postRequest('/products', {
        'name': name,
        'purchase_rate': purchaseRate,
        'sale_rate': saleRate,
        'tax_percentage': taxPercentage,
        'opening_qty': openingQty,
        'category_id': categoryId,
        'brand_id': brandId,
        'unit_id': unitId,
        'pct_code': pctCode,
        'description': description,
        'barcode': barcode,
        'barcode_auto_generated': barcodeAutoGenerated,
      });

      if (response['success'] == true) {
        await fetchProducts();
        return true;
      } else {
        _errorMessage = response['message'] ?? 'Failed to create product';
        return false;
      }
    } catch (e) {
      _errorMessage = 'Error: ${e.toString()}';
      return false;
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  // ── Update ─────────────────────────────────────────────────────────────────

  Future<bool> updateProduct({
    required int id,
    required String name,
    required double purchaseRate,
    required double saleRate,
    double taxPercentage = 0,
    double openingQty = 0,
    int? categoryId,
    int? brandId,
    int? unitId,
    String? pctCode,
    String description = '',
    String? barcode,
    bool? barcodeAutoGenerated,
  }) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      final Map<String, dynamic> data = {
        'name': name,
        'purchase_rate': purchaseRate,
        'sale_rate': saleRate,
        'tax_percentage': taxPercentage,
        'opening_qty': openingQty,
        'category_id': categoryId,
        'brand_id': brandId,
        'unit_id': unitId,
        'pct_code': pctCode,
        'description': description,
      };

      if (barcodeAutoGenerated != null) {
        data['barcode_auto_generated'] = barcodeAutoGenerated;
        if (!barcodeAutoGenerated && barcode != null) {
          data['barcode'] = barcode;
        }
      }

      final response = await _apiService.putRequest('/products/$id', data);

      if (response['success'] == true) {
        await fetchProducts();
        return true;
      } else {
        _errorMessage = response['message'] ?? 'Failed to update product';
        return false;
      }
    } catch (e) {
      _errorMessage = 'Error: ${e.toString()}';
      return false;
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  // ── Delete ─────────────────────────────────────────────────────────────────

  Future<bool> deleteProduct(int id) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      final response = await _apiService.deleteRequest('/products/$id');

      if (response['success'] == true) {
        await fetchProducts();
        return true;
      } else {
        _errorMessage = response['message'] ?? 'Failed to delete product';
        return false;
      }
    } catch (e) {
      _errorMessage = 'Error: ${e.toString()}';
      return false;
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  // ── Helpers ────────────────────────────────────────────────────────────────

  Product? getProductById(int id) {
    try {
      return _products.firstWhere((p) => p.id == id);
    } catch (_) {
      return null;
    }
  }
}